from __future__ import annotations

from datetime import date

from handoff.analysis.repo import RepoInfo
from handoff.analysis.risk import RiskMatch
from handoff.analysis.tests import TestMapping
from handoff.git.models import DiffResult

SEVERITY_ICONS = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🔵"}
CHANGE_LABELS = {"A": "Added", "M": "Modified", "D": "Deleted", "R": "Renamed", "U": "Changed"}


class PRDescriptionBuilder:
    """Build a Markdown PR description from analysis results."""

    def build(
        self,
        diff: DiffResult,
        risks: list[RiskMatch],
        mappings: list[TestMapping],
        repo_info: RepoInfo | None = None,
    ) -> str:
        sections: list[str] = []

        sections.append(self._summary(diff))
        sections.append(self._changes_table(diff))
        sections.append(self._risk_section(risks))
        sections.append(self._testing_section(mappings, risks))
        sections.append(self._checklist(risks))
        sections.append(self._footer())

        return "\n\n".join(s for s in sections if s)

    # ------------------------------------------------------------------

    def _summary(self, diff: DiffResult) -> str:
        commit_count = len(diff.commits)
        file_count = len(diff.changed_files)
        commit_line = (
            f"\n\n**Commits ({commit_count}):**\n"
            + "\n".join(f"- {c.sha[:7]} {c.message}" for c in diff.commits[:10])
            if diff.commits
            else ""
        )
        return (
            f"## Summary\n\n"
            f"<!-- Describe what this PR does and why. -->\n\n"
            f"This PR changes {file_count} file(s) on `{diff.branch}` compared to `{diff.base_branch}`."
            f"{commit_line}"
        )

    def _changes_table(self, diff: DiffResult) -> str:
        rows = ["## Changes\n", "| File | Change | +/- |", "|------|--------|-----|"]
        for fc in sorted(diff.changed_files, key=lambda f: f.path):
            label = CHANGE_LABELS.get(fc.change_type.value, "Changed")
            stats = f"+{fc.additions} / -{fc.deletions}"
            rows.append(f"| `{fc.path}` | {label} | {stats} |")
        return "\n".join(rows)

    def _risk_section(self, risks: list[RiskMatch]) -> str:
        category_risks = [r for r in risks if r.risk_type == "CATEGORY"]
        if not category_risks:
            return "## Risk Areas\n\n_No high-risk file categories detected._"

        lines = ["## Risk Areas\n"]
        for r in category_risks:
            icon = SEVERITY_ICONS.get(r.severity, "⚪")
            lines.append(f"- {icon} **{r.severity}: {r.category}** — `{r.file_path}`")
        return "\n".join(lines)

    def _testing_section(self, mappings: list[TestMapping], risks: list[RiskMatch]) -> str:
        lines = ["## Testing\n"]

        all_commands: list[str] = []
        for m in mappings:
            all_commands.extend(m.suggested_commands)
        all_commands = list(dict.fromkeys(all_commands))

        if all_commands:
            for cmd in all_commands:
                lines.append(f"- [ ] `{cmd}`")
        else:
            lines.append("- [ ] Run the relevant test suite")

        lines.append("- [ ] Manual testing: <!-- describe what you tested -->")

        # Add migration note if relevant
        if any(r.category == "migration" for r in risks if r.risk_type == "CATEGORY"):
            lines.append("- [ ] Verify migration runs cleanly and has a rollback plan")

        return "\n".join(lines)

    def _checklist(self, risks: list[RiskMatch]) -> str:
        debug_count = len([r for r in risks if r.risk_type == "DEBUG"])
        todo_count = len([r for r in risks if r.risk_type == "TODO"])
        secret_count = len([r for r in risks if r.risk_type == "SECRET"])

        def item(text: str, warn: bool = False) -> str:
            prefix = "- [x]" if not warn else "- [ ] ⚠"
            return f"{prefix} {text}"

        lines = [
            "## Checklist\n",
            item(f"No debug statements in diff", warn=debug_count > 0)
            + (f" ({debug_count} found)" if debug_count > 0 else ""),
            item("No TODO/FIXME introduced", warn=todo_count > 0)
            + (f" ({todo_count} found)" if todo_count > 0 else ""),
            item("No hardcoded secrets", warn=secret_count > 0)
            + (f" ({secret_count} possible)" if secret_count > 0 else ""),
            "- [ ] Tests added or updated",
            "- [ ] PR description explains the why, not just the what",
            "- [ ] Relevant docs updated (if applicable)",
        ]
        return "\n".join(lines)

    def _footer(self) -> str:
        return "---\n*Generated by [handoff-cli](https://github.com/kennedym/handoff-cli)*"
